### ISSUE TITLE
Minor bug in the code for torch_unet_kvasir, which leads to run-time error due to CUDA, if running on CPU mode.

### ISSUE THREAD

**Issue by saransh09** [intel/openfl#59]
In the openfl/openfl-workspace/torch_unet_kvasir/code/fed_unet_runner.py
Line23 : It should be 
`def __init__(self, device='cpu', **kwargs):`
Instead of 
`def __init__(self, device='cuda', **kwargs):`

This seems to be a typo, as in the description it is written that the default device is set to be 'cpu'.

Without this change, one would encounter a run-time error due to CUDA not found.

**Comment by alexey-gruzdev** [comment]
@saransh09 thanks for bringing this up! Fixed in https://github.com/intel/openfl/commit/65728d8b09ea45092cef91f11127021288b5ae20 .

**Comment by saransh09** [comment]
@alexey-gruzdev can you please make this fix in the main branch as well?
I have to prepare for a demo, and when I fresh pip install the library, this problem persists. I guess pip pulls the code from main branch, if I am not wrong.

**Comment by alexey-gruzdev** [comment]
@saransh09 we are preparing new release package and as a part of this activity we will merge develop in master and fix also will be available through pip. Stay tuned, we should have it pretty soon.
